# Configurações de Banco de Dados (Ambiente Local)
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurações de E-mail (Credenciais Reais)
# Use a nova senha de app que você gerar após trocar a anterior
spring.mail.username=viniciusvilanova7@gmail.com
spring.mail.password=whnv ogmt hfik gytx